package com.Heart2Hub.Heart2Hub_Backend.enumeration;

public enum AllergenEnum {
    AMOXICILLIN,
    PENICILLIN_V,
    SULFAMETHOXAZOLE,
    ASPIRIN,
    IBUPROFEN,
    PHENYTOIN,
    LAMOTRIGINE,
    LISINOPRIL,
    LIDOCAINE,
    INFLIXIMAB,
    BENZALKONIUM_CHLORIDE,
    TARTRAZINE,
    LACTOSE,
    GLUTEN,
    GELATIN,
    POLYETHYLENE_GLYCOL,
    SOY,
    EGG,
    PEANUT_OIL,
    PROPYLENE_GLYCOL,

}
