package com.Heart2Hub.Heart2Hub_Backend.enumeration;

public enum StaffRoleEnum {
  ADMIN,
  DOCTOR,
  NURSE,
  PHARMACIST,
  DIAGNOSTIC_RADIOGRAPHERS,
  DIETITIANS,
  OCCUPATIONAL_THERAPISTS,
  MEDICAL_LABORATORY_TECHNOLOGISTS,
  PHYSIOTHERAPISTS,
  PODIATRISTS,
  PSYCHOLOGISTS,
  PROSTHETISTS,
  ORTHOTISTS,
  RADIATION_THERAPISTS,
  RESPIRATORY_THERAPISTS,
  SPEECH_THERAPISTS,
  AUDIOLOGISTS,
  MEDICAL_SOCIAL_WORKERS,
  ORTHOPTISTS
}
