package com.Heart2Hub.Heart2Hub_Backend.enumeration;

public enum TreatmentPlanTypeEnum {
    CHRONIC_DISEASE_MANAGEMENT_PLAN,
    DIETARY_AND_NUTRITIONAL_PLAN,
    EDUCATIONAL_PLAN,
    EMERGENCY_ACTION_PLAN,
    FOLLOW_UP_AND_MONITORING,
    LIFESTYLE_MODIFICATION_PLAN,
    MEDICATION_MANAGEMENT_PLAN,
    OCCUPATIONAL_THERAPY_PLAN,
    PAIN_MANAGEMENT_PLAN,
    PALLIATIVE_CARE_PLAN,
    PHYSICAL_THERAPY_PLAN,
    PREVENTIVE_CARE_PLAN,
    PSYCHOTHERAPY_OR_COUNSELLING_PLAN,
    REHABILITATION_PLAN,
    SURGICAL_TREATMENT_PLAN
}
